version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/mgapi/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy_dev.sh
      timeout: 60
      runas: ec2-user